version: '3.8'
services:
  ragflow-server:
    build: .
    container_name: ragflow-server
    ports:
      - "5000:5000"
    depends_on:
      - ragflow-mysql
      - ragflow-redis
      - ragflow-minio
      - ragflow-es-01
      - ragflow-neo4j
    volumes:
      - ./outputs:/app/outputs
      - ./docker/entrypoint.sh:/ragflow/entrypoint.sh
    environment:
      - FLASK_ENV=production
      - SUPABASE_URL=https://ilgsekabtgymxwgxbkok.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZ3Nla2FidGd5bXh3Z3hia29rIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTg2NjAyNiwiZXhwIjoyMDc1NDQyMDI2fQ.WQPe4xeqi8ATFhmd8dNPuD_5VXgbg7SVHThJN4S-eZE
      - NEO4J_URI=bolt://ragflow-neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=graphiti_password
      # Multi-Provider LLM Configuration
      - LLM_PROVIDER=google
      # Google Gemini (PRIMARY for entity extraction via Graphiti)
      - GOOGLE_API_KEY=AIzaSyCTxRlT_24HYYfpLJACYxW5uS3tnq0vzJI
      - GOOGLE_MODEL=gemini-2.5-flash
      # Ollama (for embeddings - http://host.docker.internal:11434)
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen2.5-coder:3b
      - OLLAMA_EMBED_MODEL=nomic-embed-text
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For accessing host Ollama on Linux

  ragflow-mysql:
    image: mysql:8.0.39
    container_name: ragflow-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ragflow
      MYSQL_USER: ragflow
      MYSQL_PASSWORD: ragflowpassword
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/data/application/init.sql

  ragflow-redis:
    image: valkey/valkey:8
    container_name: ragflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  ragflow-minio:
    image: quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: ragflow-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  ragflow-es-01:
    image: elasticsearch:8.11.3
    container_name: ragflow-es-01
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"

  ragflow-neo4j:
    image: neo4j:5.18.0
    container_name: ragflow-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/graphiti_password
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_memory_heap_max__size=2G
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

volumes:
  neo4j-data:
  neo4j-logs:
