name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: https://dummy.supabase.co
      SUPABASE_KEY: dummy_key
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: dummy_password
      GOOGLE_API_KEY: dummy_key
      OLLAMA_HOST: http://localhost:11434
      OLLAMA_MODEL: dummy_model
      OLLAMA_EMBED_MODEL: dummy_embed
      RAGFLOW_API_KEY: changeme

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest test_*.py -v

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ragflow-slim-graphs .

    - name: Test Docker build
      run: |
        docker run --rm ragflow-slim-graphs python -c "import app; print('Build successful')"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ragflow-slim-graphs:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/ragflow-slim-graphs:latest