name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: https://dummy.supabase.co
      SUPABASE_KEY: dummy_key
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: dummy_password
      GOOGLE_API_KEY: dummy_key
      OLLAMA_HOST: http://localhost:11434
      OLLAMA_MODEL: dummy_model
      OLLAMA_EMBED_MODEL: dummy_embed
      RAGFLOW_API_KEY: changeme

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest test_*.py -v

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ragflow-slim-graphs .

    - name: Test Docker build
      run: |
        docker run --rm ragflow-slim-graphs python -c "import app; print('Build successful')"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Evaluate Docker Hub credentials
      id: dockerhub
      run: |
        if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
          echo "Docker Hub secrets not configured. Skipping deployment."
          echo "Please configure DOCKERHUB_USERNAME and DOCKERHUB_TOKEN in repository settings."
          echo "has_credentials=false" >> "$GITHUB_OUTPUT"
        else
          echo "has_credentials=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Login to Docker Hub
      if: steps.dockerhub.outputs.has_credentials == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.dockerhub.outputs.has_credentials == 'true'
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/ragflow-slim-graphs:latest .
        docker push ${{ env.DOCKERHUB_USERNAME }}/ragflow-slim-graphs:latest